-- SQL Manager Lite for PostgreSQL 6.6.1.58897
-- ---------------------------------------
-- Host      : localhost
-- Database  : distribuida
-- Version   : PostgreSQL 17.4 on x86_64-windows, compiled by msvc-19.41.34120, 64-bit



SET check_function_bodies = false;
--
-- Structure for table flyway_schema_history (OID = 31140) : 
--
SET search_path = public, pg_catalog;
CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version varchar(50),
    description varchar(200) NOT NULL,
    type varchar(20) NOT NULL,
    script varchar(1000) NOT NULL,
    checksum integer,
    installed_by varchar(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
)
WITH (oids = false);
ALTER TABLE ONLY public.flyway_schema_history ALTER COLUMN installed_rank SET STATISTICS 0;
ALTER TABLE ONLY public.flyway_schema_history ALTER COLUMN version SET STATISTICS 0;
ALTER TABLE ONLY public.flyway_schema_history ALTER COLUMN description SET STATISTICS 0;
ALTER TABLE ONLY public.flyway_schema_history ALTER COLUMN type SET STATISTICS 0;
ALTER TABLE ONLY public.flyway_schema_history ALTER COLUMN script SET STATISTICS 0;
ALTER TABLE ONLY public.flyway_schema_history ALTER COLUMN checksum SET STATISTICS 0;
ALTER TABLE ONLY public.flyway_schema_history ALTER COLUMN installed_by SET STATISTICS 0;
ALTER TABLE ONLY public.flyway_schema_history ALTER COLUMN installed_on SET STATISTICS 0;
ALTER TABLE ONLY public.flyway_schema_history ALTER COLUMN execution_time SET STATISTICS 0;
ALTER TABLE ONLY public.flyway_schema_history ALTER COLUMN success SET STATISTICS 0;
--
-- Structure for table authors (OID = 31150) : 
--
CREATE TABLE public.authors (
    id serial NOT NULL,
    name varchar(255),
    version integer
)
WITH (oids = false);
ALTER TABLE ONLY public.authors ALTER COLUMN id SET STATISTICS 0;
ALTER TABLE ONLY public.authors ALTER COLUMN name SET STATISTICS 0;
ALTER TABLE ONLY public.authors ALTER COLUMN version SET STATISTICS 0;
--
-- Structure for table books_authors (OID = 31217) : 
--
CREATE TABLE public.books_authors (
    books_isbn varchar(255) NOT NULL,
    authors_id integer NOT NULL
)
WITH (oids = false);
ALTER TABLE ONLY public.books_authors ALTER COLUMN books_isbn SET STATISTICS 0;
ALTER TABLE ONLY public.books_authors ALTER COLUMN authors_id SET STATISTICS 0;
--
-- Structure for table books (OID = 31242) : 
--
CREATE TABLE public.books (
    isbn varchar(255) NOT NULL,
    title varchar(128),
    price numeric(12,2),
    version integer
)
WITH (oids = false);
ALTER TABLE ONLY public.books ALTER COLUMN isbn SET STATISTICS 0;
ALTER TABLE ONLY public.books ALTER COLUMN title SET STATISTICS 0;
ALTER TABLE ONLY public.books ALTER COLUMN price SET STATISTICS 0;
ALTER TABLE ONLY public.books ALTER COLUMN version SET STATISTICS 0;
--
-- Structure for table inventory (OID = 31247) : 
--
CREATE TABLE public.inventory (
    isbn varchar(255) NOT NULL,
    sold integer,
    supplied integer
)
WITH (oids = false);
ALTER TABLE ONLY public.inventory ALTER COLUMN isbn SET STATISTICS 0;
ALTER TABLE ONLY public.inventory ALTER COLUMN sold SET STATISTICS 0;
ALTER TABLE ONLY public.inventory ALTER COLUMN supplied SET STATISTICS 0;
--
-- Structure for table customers (OID = 31263) : 
--
CREATE TABLE public.customers (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(64),
    email varchar(64),
    version integer
)
WITH (oids = false);
ALTER TABLE ONLY public.customers ALTER COLUMN id SET STATISTICS 0;
ALTER TABLE ONLY public.customers ALTER COLUMN name SET STATISTICS 0;
ALTER TABLE ONLY public.customers ALTER COLUMN email SET STATISTICS 0;
ALTER TABLE ONLY public.customers ALTER COLUMN version SET STATISTICS 0;
--
-- Structure for table line_items (OID = 31269) : 
--
CREATE TABLE public.line_items (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id integer,
    quantity integer,
    isbn varchar(64)
)
WITH (oids = false);
ALTER TABLE ONLY public.line_items ALTER COLUMN id SET STATISTICS 0;
ALTER TABLE ONLY public.line_items ALTER COLUMN order_id SET STATISTICS 0;
ALTER TABLE ONLY public.line_items ALTER COLUMN quantity SET STATISTICS 0;
ALTER TABLE ONLY public.line_items ALTER COLUMN isbn SET STATISTICS 0;
--
-- Structure for table purchase_orders (OID = 31275) : 
--
CREATE TABLE public.purchase_orders (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id integer,
    total integer,
    status smallint,
    placed_on timestamp without time zone,
    delivered_on timestamp without time zone
)
WITH (oids = false);
ALTER TABLE ONLY public.purchase_orders ALTER COLUMN id SET STATISTICS 0;
ALTER TABLE ONLY public.purchase_orders ALTER COLUMN customer_id SET STATISTICS 0;
ALTER TABLE ONLY public.purchase_orders ALTER COLUMN total SET STATISTICS 0;
ALTER TABLE ONLY public.purchase_orders ALTER COLUMN status SET STATISTICS 0;
ALTER TABLE ONLY public.purchase_orders ALTER COLUMN placed_on SET STATISTICS 0;
ALTER TABLE ONLY public.purchase_orders ALTER COLUMN delivered_on SET STATISTICS 0;
--
-- Definition for index flyway_schema_history_s_idx (OID = 31148) : 
--
CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);
--
-- Definition for index flyway_schema_history_pk (OID = 31146) : 
--
ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk
    PRIMARY KEY (installed_rank);
--
-- Definition for index author_pkey (OID = 31154) : 
--
ALTER TABLE ONLY public.authors
    ADD CONSTRAINT author_pkey
    PRIMARY KEY (id);
--
-- Definition for index pk_books_authors (OID = 31220) : 
--
ALTER TABLE ONLY public.books_authors
    ADD CONSTRAINT pk_books_authors
    PRIMARY KEY (books_isbn, authors_id);
--
-- Definition for index fk_books_authors_on_authors (OID = 31222) : 
--
ALTER TABLE ONLY public.books_authors
    ADD CONSTRAINT fk_books_authors_on_authors
    FOREIGN KEY (authors_id) REFERENCES authors(id);
--
-- Definition for index pk_books (OID = 31245) : 
--
ALTER TABLE ONLY public.books
    ADD CONSTRAINT pk_books
    PRIMARY KEY (isbn);
--
-- Definition for index pk_inventory (OID = 31250) : 
--
ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT pk_inventory
    PRIMARY KEY (isbn);
--
-- Definition for index fk_inventory_on_isbn (OID = 31252) : 
--
ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT fk_inventory_on_isbn
    FOREIGN KEY (isbn) REFERENCES books(isbn);
--
-- Definition for index fk_books_authors_on_books (OID = 31257) : 
--
ALTER TABLE ONLY public.books_authors
    ADD CONSTRAINT fk_books_authors_on_books
    FOREIGN KEY (books_isbn) REFERENCES books(isbn);
--
-- Definition for index pk_customers (OID = 31266) : 
--
ALTER TABLE ONLY public.customers
    ADD CONSTRAINT pk_customers
    PRIMARY KEY (id);
--
-- Definition for index pk_line_items (OID = 31272) : 
--
ALTER TABLE ONLY public.line_items
    ADD CONSTRAINT pk_line_items
    PRIMARY KEY (id);
--
-- Definition for index pk_purchase_orders (OID = 31278) : 
--
ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT pk_purchase_orders
    PRIMARY KEY (id);
--
-- Definition for index fk_line_items_on_order (OID = 31280) : 
--
ALTER TABLE ONLY public.line_items
    ADD CONSTRAINT fk_line_items_on_order
    FOREIGN KEY (order_id) REFERENCES purchase_orders(id);
--
-- Definition for index fk_line_items_on_book (OID = 31285) : 
--
ALTER TABLE ONLY public.line_items
    ADD CONSTRAINT fk_line_items_on_book
    FOREIGN KEY (isbn) REFERENCES books(isbn);
--
-- Definition for index fk_purchase_orders_on_customer (OID = 31290) : 
--
ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT fk_purchase_orders_on_customer
    FOREIGN KEY (customer_id) REFERENCES customers(id);
--
-- Comments
--
COMMENT ON SCHEMA public IS 'standard public schema';