CREATE TABLE customers
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(64),
    email   VARCHAR(64),
    version INTEGER,
    CONSTRAINT pk_customers PRIMARY KEY (id)
);
CREATE TABLE line_items
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id INTEGER,
    quantity INTEGER,
    isbn     VARCHAR(64),
    CONSTRAINT pk_line_items PRIMARY KEY (id)
);
CREATE TABLE purchase_orders
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id  INTEGER,
    total        INTEGER,
    status       SMALLINT,
    placed_on    TIMESTAMP WITHOUT TIME ZONE,
    delivered_on TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_purchase_orders PRIMARY KEY (id)
);
ALTER TABLE line_items
    ADD CONSTRAINT FK_LINE_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES purchase_orders (id);
ALTER TABLE line_items
    ADD CONSTRAINT FK_LINE_ITEMS_ON_BOOK FOREIGN KEY (isbn) REFERENCES books (isbn);
ALTER TABLE purchase_orders
    ADD CONSTRAINT FK_PURCHASE_ORDERS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (id);