api:
  insecure: true
  dashboard: true

entryPoints:
  http:
    address: ":80"
  traefik:
    address: ":8888"
    
providers:
#  file:
#    filename: app-static.yml
#    watch: true
    consulCatalog:
      refreshInterval: 10s
      exposedByDefault: false
      endpoint:
        address: 127.0.0.1:8500
